long Pow2(unsigned int x, unsigned int y);
int IsPow2(unsigned int n);
int IsPow2Loop(unsigned int n);
void AddOneNoOpe(int *n);
void OnlyThree(unsigned int *a, int len);
void PrintIsThreeBits(int num);
unsigned char ByteMirrorLoop(unsigned char num);
unsigned char ByteMirror(unsigned char b);
int IsSecondAndSixth(unsigned char num);
int IsAtLeastSecondAndSixth(unsigned char num);
unsigned char SwapThirdAndFifth(unsigned char num);
unsigned int ClosestDeviseAbleBy16(unsigned int num);
void SwapWithtoutTemp(int *num1, int *num2);
unsigned int CountWithLoop(unsigned int num);
unsigned int CountNoLoop(unsigned int n);
void PrintBitsFLoat(float *num);
int IsBit(int a, int loc);
