USE computerStore;
-- INSERT INTO computer (
--         modelID,
--         RAM,
--         procssorSpeed,
--         HDspace,
--         CDID,
--         screenSize,
--         vers,
--         price,
--         computerID
--     )
-- VALUES (
--         412,
--         32,
--         632,
--         600,
--         232,
--         32,
--         0,
--         5001,
--         430
--     );
-- INSERT INTO manufacturers (manufacturerID, nameOfManfacturer)
-- VALUES (4323324, 'dsasd');
-- INSERT INTO printers (printerID, manufacturerID, isBlackAndWhite)
-- VALUES (432, 43234, 1);